### ISSUE TITLE
Removing complexity

### ISSUE THREAD

**Issue by Seccour** [niteshbalusu11/lndboss#111]
Complex passwords (passwords that include numbers, special characters, uppercase and smaller case characters) are less secure than long, lower case only passphrases because such complexity force people to reuse the same passwords everywhere unless they have a password manager, which are sometimes not available on all the platforms you would need them on.

Either remove the checks for the password, or only keep a minimum length

**Comment by niteshbalusu11** [comment]
interesting point. I'll probably just switch to a length check.

**Comment by niteshbalusu11** [comment]
It's been fixed, docker image will take another 20mins to build. Though this will only apply for new sign ups. already registered people it won't make any difference.
