### ISSUE TITLE
Auto fees don't work like expected

### ISSUE THREAD

**Issue by michaelWuensch** [niteshbalusu11/lndboss#142]
Hi, I wanted to automate my fees based on 2 rules:
![image](https://user-images.githubusercontent.com/15313630/217655958-805c83f6-1dd2-40da-aab4-8ca7440b6977.png)

First one works, second one doesn't. What am I doing wrong?
The second one should affect a channel that has 100% inbound, but it doesn't no matter what I set the fees to.
I also have to admit, that I find the explanations quite confusing. Why can I add multiple values in each field? What happens if I set 2 different Base fees in the same field? Which one is chosen?

**Comment by niteshbalusu11** [comment]
It should work in theory. Have to check what's going on. 
Do you mind sharing the channel details from command line? Or you can give me the result of getChannel from the "Call" command in commands list. 

If you add 2 base fees in the same field, then you also have to add two outbound/capacity ratios. It just applies them in order just like having them in separate rows.

**Comment by michaelWuensch** [comment]
Sure:
I anonymized node pubkeys and transaction id.

id: "775512x613x1"
capacity: 2500000
policies:
  - base_fee_mtokens: "0"
    cltv_delta: 40
    fee_rate: 0
    is_disabled: false
    max_htlc_mtokens: "2475000000"
    min_htlc_mtokens: "1000"
    public_key: "XXXXXXXXX"
    updated_at: "2023-02-08T23:09:25.000Z"
  - base_fee_mtokens: "1000"
    cltv_delta: 40
    fee_rate: 0
    is_disabled: false
    max_htlc_mtokens: "2475000000"
    min_htlc_mtokens: "1000"
    public_key: "XXXXXXXXXX"
    updated_at: "2023-02-08T12:38:08.000Z"
transaction_id: "XXXXXX"
transaction_vout: 1
updated_at: "2023-02-08T23:09:25.000Z"

By the way I also tried to change the fee manually for this channel with Ride the Lightning and it worked flawlessly.
Right now I only have one channel that fulfills the rules that do not get executed.
I furthermore now tried to do everything in one row. Same result.

**Comment by niteshbalusu11** [comment]
You said this channel is mostly remote? Because you hid balances.

**Comment by niteshbalusu11** [comment]
The condition for limits in the outbound/capacity ratio is `> && <=`
Have you verified that?

**Comment by michaelWuensch** [comment]
Thanks for your answers!
I don't have time to test this again before tomorrow.

I did not hide any balances, that is all that getChannel spit out using the call command.

But if the condition is actually > && <= than this ist the issue. In my second rule this would be 0 > && <= 0.1 with the ratio being exactly 0.
Therefore the rule is never applied.

**Comment by niteshbalusu11** [comment]
Maybe I should make an exception for 0 or change the condition a little. I can’t use both >= and <= because it won’t make sense. 
I will work on fixing it.

**Comment by michaelWuensch** [comment]
I actually expected it includes both bounds. To me it makes sense. Which rule is the dominant one then depends on execution order.
But making an exception for 0 is also fine.

**Comment by niteshbalusu11** [comment]
Including both bounds would be a breaking change because all existing people who use it have to make changes, 0 exception is easier for a new release.

**Comment by niteshbalusu11** [comment]
Released a minor version where this bug has been fixed. Will work with Umbrel and other appstore guys to have the app updated but you can install yourself.
