### ISSUE TITLE
Add screenshot to README

### ISSUE THREAD

**Issue by CypherPoet** [niteshbalusu11/lndboss#21]
Being a GUI, I feel like it would be extremely helpful for interested users to have a screenshot of the interface in the README.

**Comment by niteshbalusu11** [comment]
A screenshot for setting it up?

**Comment by CypherPoet** [comment]
I was mainly envisioning something that depicts the GUI in action -- so probably something that shows it after it's been set up and running.

**Comment by niteshbalusu11** [comment]
Cool ok.

**Comment by niteshbalusu11** [comment]
Added.

https://github.com/niteshbalusu11/lndboss#demo
